#This layout inspired by popular economy games
title:
  extends: base_title
  x: 160
  #y: 90
  y: 75
  width: 495
  #height: 50

art:
  x: 75
  y: 150
  width: 675
  height: 520

description:
  x: 100
  y: 675
  width: 625
  height: 275
  valign: middle #top
  align: center
  font_size: 12
 # markup: true
desc: # alias
  extends: description

deck_name:
  x: 90
  y: 955
  width: 645
  height: 50
  font_size: 12
  color: 'gray'
  align: center

embedded_icon:
  width: 70
  height: 70
  dy: -10

lower_right:
  x: 645
  y: 955
  width: 75
  height: 75
  font_size: 12
  valign: bottom
  align: right
cost: #alias
  font_size: 14
  extends: lower_right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
  color: 'gray'
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
# 300 dpi
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
# 300 dpi
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3
