#This layout inspired by popular economy games
title:
  extends: base_title
  x: 175
  #y: 90
  y: 85
  width: 480
  #height: 50

base-type:
  x: 85
  y: 85
  width: 75
  height: 75

art:
  x: 75
  y: 150
  width: 675
  height: 520

description:
  x: 100
  y: 475
  width: 625
  height: 250
  valign: middle #top
  align: center
  font_size: 11
 # markup: true
desc: # alias
  extends: description

combo_effect:
  extends: description
  x: 235
  y: 750
  width: 465
  height: 175

combo_box:
  extends: combo_effect
  fill_color: '#efefef'
  stroke_color: '#efefef'
  x: 100
  y: 750
  width: 625
  height: 175

combo_box_none:
  extends: combo_box
  fill_color: '#0000'
  stroke_color: '#0000'

combo_divider_line:
  x1: 220
  y1: 785
  x2: 220
  y2: 890
  stroke_color: 'black'

# combo_trigger:
#   extends: base-type
#   y: 800

deck_name:
  x: 90
  y: 955
  width: 645
  height: 50
  font_size: 12
  color: 'gray'
  align: center

embedded_icon:
  width: 70
  height: 70
  dy: -10

lower_right:
  x: 625
  y: 935
  width: 95
  height: 95
  font_size: 12
  valign: bottom
  align: right
cost: #alias
  font_size: 15
  extends: lower_right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
  color: 'gray'
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
# 300 dpi
cut:
  x: 37.5
  y: 37.5
  #width: 675
  #height: 975
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
# 300 dpi
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3

none:
  fill_color: '#0000'
  stroke_color: '#0000'
  x: 0
  y: 0
  width: 0
  height: 0